/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Information of a NWDAF NF Instance
type NwdafInfo struct {
	EventIds        []EventId        `json:"eventIds,omitempty" yaml:"eventIds" bson:"eventIds,omitempty"`
	NwdafEvents     []NwdafEvent     `json:"nwdafEvents,omitempty" yaml:"nwdafEvents" bson:"nwdafEvents,omitempty"`
	TaiList         []Tai            `json:"taiList,omitempty" yaml:"taiList" bson:"taiList,omitempty"`
	TaiRangeList    []TaiRange       `json:"taiRangeList,omitempty" yaml:"taiRangeList" bson:"taiRangeList,omitempty"`
	NwdafCapability *NwdafCapability `json:"nwdafCapability,omitempty" yaml:"nwdafCapability" bson:"nwdafCapability,omitempty"`
	// indicating a time in seconds.
	AnalyticsDelay     int32                   `json:"analyticsDelay,omitempty" yaml:"analyticsDelay" bson:"analyticsDelay,omitempty"`
	ServingNfSetIdList []string                `json:"servingNfSetIdList,omitempty" yaml:"servingNfSetIdList" bson:"servingNfSetIdList,omitempty"`
	ServingNfTypeList  []NrfNfManagementNfType `json:"servingNfTypeList,omitempty" yaml:"servingNfTypeList" bson:"servingNfTypeList,omitempty"`
	MlAnalyticsList    []MlAnalyticsInfo       `json:"mlAnalyticsList,omitempty" yaml:"mlAnalyticsList" bson:"mlAnalyticsList,omitempty"`
}
