package models

var ValidNfType = map[NfType]bool{
	NfType_NRF:      true,
	NfType_UDM:      true,
	NfType_AMF:      true,
	NfType_SMF:      true,
	NfType_AUSF:     true,
	NfType_NEF:      true,
	NfType_PCF:      true,
	NfType_SMSF:     true,
	NfType_NSSF:     true,
	NfType_UDR:      true,
	NfType_LMF:      true,
	NfType_GMLC:     true,
	NfType__5_G_EIR: true,
	NfType_SEPP:     true,
	NfType_UPF:      true,
	NfType_N3_IWF:   true,
	NfType_AF:       true,
	NfType_UDSF:     true,
	NfType_BSF:      true,
	NfType_CHF:      true,
	NfType_NWDAF:    true,
}
